#!/usr/bin/python3

import sys
import subprocess
import time
from pathlib import Path


def wgetf(file: str, interval: float):
    with open(file, 'r') as fp:
        urls_text = fp.read()

    urls = urls_text.split('\n')
    url_names = [ url.split(' ') for url in urls if len(url) > 0 ]

    for url, name in url_names:
        Path(name).parent.mkdir(exist_ok=True, parents=True)
        subprocess.call([ 'wget', url, '-O', name ])
        time.sleep(interval)    

if __name__ == '__main__':
    import argparse
    parser = argparse.ArgumentParser()

    parser.add_argument('file', type=str)
    parser.add_argument('interval', type=float)

    args = parser.parse_args()

    file = args.file
    interval = args.interval

    wgetf(file, interval)

