#!/usr/bin/env python3

import os
import sys
from pathlib import Path
import subprocess
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('-ss', type=str, required=True)
parser.add_argument('-to', type=str, required=True)
parser.add_argument('-i', '--input_path', type=str, required=True)
parser.add_argument('output_path', type=str)
args = parser.parse_args()

ss = args.ss
to = args.to
input_path = args.input_path
output_path = args.output_path

subprocess.run([ 'ffmpeg', '-ss', ss, '-to', to, '-i', input_path, '-map', '0', '-map_metadata', '0', '-c', 'copy', output_path], stdout=sys.stdout, stderr=sys.stderr)

