#!/usr/bin/env python3

import os
from pathlib import Path
import subprocess
import argparse

parser = argparse.ArgumentParser()
parser.add_argument('time', type=str)
args = parser.parse_args()

time_ss = args.time


cwd = Path.cwd()
files = sorted(filter(lambda p: p.is_file, cwd.iterdir()))

print(files)

for file in files:
    stem = file.stem
    ext = file.suffix
    
    output = f'{stem}_ss.png'
    print(f'{file} => {output}')

    ret = subprocess.call([ 'ffmpeg', '-y', '-ss', time_ss, '-i', file, '-vframes', '1', output ])


