#!/bin/bash

set -eu

DATE_STRING=`date '+%Y-%m-%dT%H:%M:%S%:z'`

# default
cd ~/.local/share/7DaysToDie
# flatpak
# cd ~/.var/app/com.valvesoftware.Steam/data/7DaysToDie

git add .
git commit -m "$DATE_STRING"

git push origin main

