#!/bin/bash

set -eu

DATE_STRING=`date '+%Y-%m-%dT%H:%M:%S%:z'`

# default
cd "$HOME/.local/share/Colossal Order/Cities_Skylines/Saves"
# flatpak
# cd "$HOME/.var/app/com.valvesoftware.Steam/data/Colossal Order/Cities_Skylines/Saves"

git add .
git commit -m "$DATE_STRING"

git push origin main

