#!/bin/bash

set -eu

DATE_STRING=`date '+%Y-%m-%dT%H:%M:%S%:z'`

# default
cd "$HOME/.steam/steam/steamapps/common/Kerbal Space Program/saves"
# flatpak
# cd "$HOME/.var/app/com.valvesoftware.Steam/data/Steam/steamapps/common/Kerbal Space Program/saves"

git add .
git commit -m "$DATE_STRING"

git push origin main

