#!/usr/bin/env python3

# pip3 install PyPDF2
import PyPDF2

if __name__ == '__main__':
  import argparse
  parser = argparse.ArgumentParser()
  parser.add_argument('input_files', type=str, nargs='+')
  parser.add_argument('output_file', type=str)
  args = parser.parse_args()

  merger = PyPDF2.PdfFileMerger()

  for file in args.input_files:
    merger.append(file)

  merger.write(args.output_file)
